// imports

// interfaces

import type { Metadata, Viewport } from "next";

// styles

import "../styles/global.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: "/icons/favicon.ico?v=4",
    apple: "/icons/apple-touch-icon.png?v=4",
    shortcut: "/icons/apple-touch-icon.png?v=4"
  },
};

export const viewport : Viewport = {
  width : "device-width",
  initialScale: 1
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-Slate100 md:flex md:justify-center md:items-center h-[100vh] w-full">{children}</body>
    </html>
  );
}
